apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-layouts-pvc
  namespace: keyboard-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-layouts
  namespace: keyboard-app
spec:
  selector:
    matchLabels:
      app: postgres-layouts
  template:
    metadata:
      labels:
        app: postgres-layouts
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: layoutsdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-layouts-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-layouts-storage
          persistentVolumeClaim:
            claimName: postgres-layouts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-layouts
  namespace: keyboard-app
spec:
  selector:
    app: postgres-layouts
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
